# Generated by Django 4.2 on 2023-05-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_worn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='worn',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='worn',
            name='date',
            field=models.DateField(verbose_name='Date used:'),
        ),
        migrations.AddField(
            model_name='handbag',
            name='items',
            field=models.ManyToManyField(to='main_app.item'),
        ),
    ]
